export const BUCKET_ADD_ASK_FAIL = "BUCKET_ADD_ASK_FAIL";
export const BUCKET_ADD_ASK = "BUCKET_ADD_ASK";
export const BUCKET_REMOVE_ASK = "BUCKET_REMOVE_ASK";
export const BUCKET_SAVE_COMPLETE_ADDRESS = "BUCKET_SAVE_COMPLETE_ADDRESS";
export const BUCKET_SAVE_PAYMENT_METHOD = "BUCKET_SAVE_PAYMENT_METHOD";
export const BUCKET_EMPTY = "BUCKET_EMPTY";
