export const PLEA_CREATE_REQUEST = 'PLEA_CREATE_REQUEST';
export const PLEA_CREATE_SUCCESS = 'PLEA_CREATE_SUCCESS';
export const PLEA_CREATE_FAIL = 'PLEA_CREATE_FAIL';
export const PLEA_CREATE_RESET = 'PLEA_CREATE_RESET';

export const PLEA_PAY_REQUEST = 'PLEA_PAY_REQUEST';
export const PLEA_PAY_SUCCESS = 'PLEA_PAY_SUCCESS';
export const PLEA_PAY_FAIL = 'PLEA_PAY_FAIL';
export const PLEA_PAY_RESET = 'PLEA_PAY_RESET';

export const PLEA_DELIVER_REQUEST = 'PLEA_DELIVER_REQUEST';
export const PLEA_DELIVER_SUCCESS = 'PLEA_DELIVER_SUCCESS';
export const PLEA_DELIVER_FAIL = 'PLEA_DELIVER_FAIL';
export const PLEA_DELIVER_RESET = 'PLEA_DELIVER_RESET';

export const PLEA_DETAILS_REQUEST = 'PLEA_DETAILS_REQUEST';
export const PLEA_DETAILS_SUCCESS = 'PLEA_DETAILS_SUCCESS';
export const PLEA_DETAILS_FAIL = 'PLEA_DETAILS_FAIL';

export const PLEA_MINE_LIST_REQUEST = 'PLEA_MINE_LIST_REQUEST';
export const PLEA_MINE_LIST_SUCCESS = 'PLEA_MINE_LIST_SUCCESS';
export const PLEA_MINE_LIST_FAIL = 'PLEA_MINE_LIST_FAIL';

export const PLEA_LIST_REQUEST = 'PLEA_LIST_REQUEST';
export const PLEA_LIST_SUCCESS = 'PLEA_LIST_SUCCESS';
export const PLEA_LIST_FAIL = 'PLEA_LIST_FAIL';

export const PLEA_DELETE_REQUEST = 'PLEA_DELETE_REQUEST';
export const PLEA_DELETE_SUCCESS = 'PLEA_DELETE_SUCCESS';
export const PLEA_DELETE_FAIL = 'PLEA_DELETE_FAIL';
export const PLEA_DELETE_RESET = 'PLEA_DELETE_RESET';

export const PLEA_SUMMARY_REQUEST = 'PLEA_SUMMARY_REQUEST';
export const PLEA_SUMMARY_SUCCESS = 'PLEA_SUMMARY_SUCCESS';
export const PLEA_SUMMARY_FAIL = 'PLEA_SUMMARY_FAIL';