export const SCREEN_LIST_REQUEST = "SCREEN_LIST_REQUEST";
export const SCREEN_LIST_SUCCESS = "SCREEN_LIST_SUCCESS";
export const SCREEN_LIST_FAIL = "SCREEN_LIST_FAIL";

export const SCREEN_DETAILS_REQUEST = "SCREEN_DETAILS_REQUEST";
export const SCREEN_DETAILS_SUCCESS = "SCREEN_DETAILS_SUCCESS";
export const SCREEN_DETAILS_FAIL = "SCREEN_DETAILS_FAIL";

export const SCREEN_CREATE_REQUEST = 'SCREEN_CREATE_REQUEST';
export const SCREEN_CREATE_SUCCESS = 'SCREEN_CREATE_SUCCESS';
export const SCREEN_CREATE_FAIL = 'SCREEN_CREATE_FAIL';
export const SCREEN_CREATE_RESET = 'SCREEN_CREATE_RESET';

export const SCREEN_REVIEW_CREATE_REQUEST = 'SCREEN_REVIEW_CREATE_REQUEST';
export const SCREEN_REVIEW_CREATE_SUCCESS = 'SCREEN_REVIEW_CREATE_SUCCESS';
export const SCREEN_REVIEW_CREATE_FAIL = 'SCREEN_REVIEW_CREATE_FAIL';
export const SCREEN_REVIEW_CREATE_RESET = 'SCREEN_REVIEW_CREATE_RESET';

export const SCREEN_UPDATE_REQUEST = 'SCREEN_UPDATE_REQUEST';
export const SCREEN_UPDATE_SUCCESS = 'SCREEN_UPDATE_SUCCESS';
export const SCREEN_UPDATE_FAIL = 'SCREEN_UPDATE_FAIL';
export const SCREEN_UPDATE_RESET = 'SCREEN_UPDATE_RESET';

export const SCREEN_DELETE_REQUEST = 'SCREEN_DELETE_REQUEST';
export const SCREEN_DELETE_SUCCESS = 'SCREEN_DELETE_SUCCESS';
export const SCREEN_DELETE_FAIL = 'SCREEN_DELETE_FAIL';
export const SCREEN_DELETE_RESET = 'SCREEN_DELETE_RESET';

export const SCREEN_CATEGORY_LIST_REQUEST = 'SCREEN_CATEGORY_LIST_REQUEST';
export const SCREEN_CATEGORY_LIST_SUCCESS = 'SCREEN_CATEGORY_LIST_SUCCESS';
export const SCREEN_CATEGORY_LIST_FAIL = 'SCREEN_CATEGORY_LIST_FAIL';